/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface NativeEndpoint {
  number: number
  direction: string
  transferType: string
  maxPacketSize: number
  interval: number
}
export interface NativeInterface {
  number: number
  alternateSetting: number
  classCode: number
  subclassCode: number
  protocolCode: number
  interfaceString?: string
  driver?: string
  endpoints: Array<NativeEndpoint>
}
export interface NativeConfiguration {
  configurationValue: number
  maxPower: number
  attributes: number
  interfaces: Array<NativeInterface>
}
export interface NativeDeviceDescriptor {
  usbVersion: string
  deviceClass: number
  deviceSubclass: number
  deviceProtocol: number
  maxPacketSize0: number
  vendorId: number
  productId: number
  deviceVersion: string
  manufacturerString?: string
  productString?: string
  serialNumberString?: string
  numConfigurations: number
}
export interface NativeUsbDevice {
  busNumber: number
  deviceAddress: number
  portPath: string
  speed: string
  vendorId: number
  productId: number
  manufacturer?: string
  product?: string
  serialNumber?: string
  deviceClass: number
  deviceSubclass: number
  deviceProtocol: number
  sysfsPath: string
  descriptor: NativeDeviceDescriptor
  configurations: Array<NativeConfiguration>
  rawDescriptors: Array<number>
}
export declare function listDevices(): Array<NativeUsbDevice>
export declare function getDeviceDescriptor(sysfsPath: string): NativeUsbDevice
export declare function getRawDescriptor(sysfsPath: string): Array<number>
